[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.15"

[features]
seeds = true
skip-lint = false

[programs.localnet]
x1safu = "F2JnWVnjP1h6WG7KKUHqhp23etEJ4amdJquAcE9ecCoe"
x1safe_put_staking = "F2JnWVnjP1h6WG7KKUHqhp23etEJ4amdJquAcE9ecCoe"

[programs.testnet]
x1safu = "F2JnWVnjP1h6WG7KKUHqhp23etEJ4amdJquAcE9ecCoe"
x1safe_put_staking = "F2JnWVnjP1h6WG7KKUHqhp23etEJ4amdJquAcE9ecCoe"

[programs.mainnet]
x1safu = "F2JnWVnjP1h6WG7KKUHqhp23etEJ4amdJquAcE9ecCoe"
x1safe_put_staking = "F2JnWVnjP1h6WG7KKUHqhp23etEJ4amdJquAcE9ecCoe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.testnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://rpc.testnet.x1.xyz"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efSNESfmsQem"
