[features]
seeds = true
skip-lint = false

[programs.testnet]
x1safu = "F2JnWVnjP1h6WG7KKUHqhp23etEJ4amdJquAcE9ecCoe"

[provider]
cluster = "https://rpc.testnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
